version: '3.8'
services:
  storage:
    image: postgres:15.3
    restart: always
    environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgres
      # ports:
      # - 5432:5432
    volumes:
    - data:/var/lib/postgresql/data

  storage_init:
    image: backend
    environment:
    - DATABASE_URL=postgresql://postgres:postgres@storage:5432/postgres?schema=public
    depends_on:
    - storage
    command: ["npm", "run", "migrate"]

  backend:
    image: backend
    command: ["npm", "start"]
    restart: always
    environment:
    - PORT=5000
    - DATABASE_URL=postgresql://postgres:postgres@storage:5432/postgres?schema=public
    ports:
    - 5000:5000
    depends_on:
      storage_init:
        condition: service_completed_successfully

volumes:
  data:
    driver: local
